teams:
  red:
    name: "Rouge"
    color: "&c"
    data: 14
  blue:
    name: "Bleu"
    color: "&9"
    data: 11
  green:
    name: "Vert"
    color: "&a"
    data: 5
  yellow:
    name: "Jaune"
    color: "&6"
    data: 4